name: ${project.name}
description: Play Checkers
author: desht
website: http://dev.bukkit.org/server-mods/checkers
main: me.desht.checkers.CheckersPlugin
version: ${project.version}

commands:
  checkers:
    description: A Command
    aliases: [ chk ]
    usage: |
      /<command> create board <board-name>
      /<command> delete board <board-name>

permissions:
  checkers.player:
    description: Gives access to the commands needs to play
    default: true
    children:
      checkers.commands.list.board: true
      checkers.commands.list.game: true
      checkers.commands.create.game: true
      checkers.commands.invite: true
      checkers.commands.join: true
      checkers.commands.undo: true
      checkers.commands.win: true
      checkers.commands.offer.draw: true
      checkers.commands.resign: true
      checkers.commands.move: true
      checkers.commands.stake: true
      checkers.commands.teleport: true
      checkers.commands.timecontrol: true
  checkers.admin:
    description: Gives access to all commands
    default: op
    children:
      checkers.commands.player: true
      checkers.commands.create.board: true
      checkers.commands.delete.board: true
      checkers.commands.delete.game: true
      checkers.commands.getcfg: true
      checkers.commands.setcfg: true
      checkers.commands.redraw: true
      checkers.commands.save: true
      checkers.commands.reload: true
  checkers.commands.create.board:
    description: Allow board creation
    default: op
  checkers.commands.delete.board:
    description: Allow board deletion
    default: op
  checkers.commands.delete.game:
    description: Allow game deletion
    default: op
  checkers.commands.board.set:
    description: Allow board parameters to be changed
    default: op
  checkers.commands.create.game:
    description: Allow games to be created
    default: true
  checkers.commands.getcfg:
    description: Allow plugin config to be viewed
    default: op
  checkers.commands.invite:
    description: Allow inviting players to games
    default: true
  checkers.commands.join:
    description: Allow joining of games
    default: true
  checkers.commands.list.board:
    description: Allow boards or board parameters to be listed
    default: true
  checkers.commands.list.game:
    description: Allow games or game details to be listed
    default: true
  checkers.commands.redraw:
    description: Allow redrawing of boards
    default: op
  checkers.commands.setcfg:
    description: Allow plugin config to be modified
    default: op
  checkers.commands.undo:
    description: Allow the last move in a game to be undone
    default: true
  checkers.commands.win:
    description: Allow victory to be claimed if other player has gone offline
    default: true
  checkers.commands.save:
    description: Allow persisted data to be force-saved
    default: op
  checkers.commands.reload:
    description: Allow plugin configuration and other data files to be reloaded
    default: op
  checkers.commands.offer.draw:
    description: Allow offering of draws in a game
    default: true
  checkers.commands.list.style:
    description: Allow board styles to be listed
    default: op
  checkers.commands.resign:
    description: Allow games to be resigned
    default: true
  checkers.commands.move:
    description: Allow use of the /checkers move command
    default: true
  checkers.commands.teleport:
    description: Allow teleporting to/from boards
    default: true
  checkers.commands.timecontrol:
    description: Allow time controls for a game to be changed
    default: true
  checkers.commands.stake:
    description: Allow the stake for a game to be changed
    default: true
