Game:
  boardAlreadyHasGame: "That board already has a game on it."
  AIisBusy: "That AI is currently busy playing a game."
  alertPrefix: "&6⛀ &-Game &6{0}&-: "
  autoDeleteFinished: "Finished game auto-deleted."
  autoDeleteNotStarted: "Game auto-deleted (not started within {0})."
  autoDeleteRunning: "Game auto-deleted (no move made within {0})."
  black: "Black"
  cantAffordToStart: "{0} can''t afford to play! (need {1})"
  cantAffordToJoin: "You can''t afford the stake for this game (need {0})!"
  cantWriteArchive: "Can''t write PGN archive {0}: {1}"
  currentGames: "Your current checkers games: {0}"
  gameCreated: "Checkers game &6{0}&- has been created on board &6{1}&-."
  gameDeleted: "Game &6{0}&- has been deleted."
  gameDeletedAlert: "Game deleted by &6{0}&-!"
  gameDetail:
    blackToPlay: "&8Black&- to play"
    clock: "Clock: &fWhite&-: {0}, &8Black&-: {1}"
    halfMoves: "&f{0,number,integer}&- half-moves made"
    invitation: "&6{0}&- has been invited.  Awaiting response."
    moveHistory: "&eMove history:"
    name: "&eGame {0} [{1}]:"
    openInvitation: "Game has an open invitation"
    players: "&6{0}&- (&fWhite&-) vs. &6{1}&- (&8Black&-)."
    stake: "&eStake: &f{0}"
    whiteToPlay: "&fWhite&- to play"
  gameHasStake: "This game has a stake of &f{0}&-."
  gameIsFull: "This game already has two players."
  getStakeBack: "You get your stake of {0} back."
  illegalMove: "Illegal move."
  inviteCooldown: "You must wait {0,number,integer} seconds before sending another open invitation."
  invited: " [invited: &6{0}&-]"
  inviteSent: "An invitation has been sent to &6{0}&-."
  inviteWithdrawn: "Your invitation has been withdrawn."
  joinedGame: "You have joined the checkers game &6{0}&- as &f{1}&-."
  joinPrompt: "Type &f/checkers join&- to join the game."
  joinPromptGlobal: "Type &f/checkers join {0}&- to join the game."
  lostStake: "You lost your stake of {0}."
  moveUndone: "The last move has been undone.  &f{0}&- to play."
  mustContinueJumping: "You must continue to jump."
  newTimeControlPhase: "New time control phase started: &6{0}&-."
  noActiveGame: "No active game - set one with &f/checkers game <name>&-."
  noNegativeStakes: "Negative stakes are not permitted!"
  noActiveGame: "You don't have an active game right now."
  noCurrentGames: "There are no games in progress right now."
  noGame: "(none)"
  noSuchGame: "No such game &6{0}&-."
  notInGame: "You are not in this game!"
  notInvited: "You don't have an invitation for this game."
  notStarted: "The game has not yet started."
  notYourTurn: "It is not your turn."
  nowPlayingBlack: "Side swap!  You are now playing Black."
  nowPlayingWhite: "Side swap!  You are now playing White."
  openInviteCreated: "&6{0}&e has created an open invitation to a Checkers game."
  paidStake: "You have paid a stake of {0}."
  playerJoined: "&6{0}&- has joined your game."
  playerNotOnline: "Player {0} is not online."
  playerPlayedMove: "{0}&- played [&f{1}&-].  Your move, {2}&-."
  playerBack: "{0} is back in the game!"
  playerQuit: "{0} quit.  If they don''t rejoin within {1,number,integer} seconds, you can type &f/checkers win&- to win by default."
  result:
    ABANDONED: "&6{0}&- drew with &6{1}&- (game abandoned) in a game of Checkers!"
    DRAW: "&6{0}&- drew with &6{1}&- (draw agreed) in a game of Checkers!"
    FORFEITED: "&6{0}&- beat &6{1}&- (forfeited) in a game of Checkers!"
    RESIGNED: "&6{0}&- beat &6{1}&- (resigned) in a game of Checkers!"
    WIN: "&6{0}&- beat &6{1}&- in a game of Checkers!"
  shouldBeState: "Game should be in state {0}."
  stakeCantBeChanged: "Stake cannot be changed once both players have joined."
  stakeLocked: "The stake for this game is locked and may not be changed."
  stakeTooHigh: "The maximum stake allowed is {0,number,currency}."
  started:
    - "Game started!  You are playing &f{0}&-."
    - "To move a piece, look at it while holding {1}, and left-click."
  startPrompt: "Start the game by typing &f/game start&- or pressing the &fStart&- button."
  timeControlLocked: "The time control for this game is locked may not be changed."
  timeControlWarning: "You have {0,number,integer} seconds left to move!"
  typeYesOrNo: "Type &f/chess yes&- to accept, or &f/chess no&- to decline."
  undoOfferedOther: "&6{0}&- wishes to undo their last move."
  undoOfferedYou: "You have asked &6{0}&- if you may undo your last move."
  undoAIWithStake: "You may not undo moves when playing for a stake against the computer."
  white: "White"
  youAreInvited: "You have been invited to this game by &6{0}&-."
  youPlayed: "You played &f{0}-{1}&-."
  yourMove: "It is your move &f({0})&-."
  youWon: "You have won {0}!"

Board:
  allBoardsRedrawn: All boards have been redrawn.
  boardCantBeDeleted: Board &6{0}&- cannot be deleted because it has a game (&6{1}&-).
  boardCreated: Board &6{0}&- has been created at &f{1}&-.
  boardCreationCancelled: Board creation has been cancelled.
  boardCreationPrompt: Left-click a block to create board &6{0}&-.  Right-click to cancel.
  boardDeleted: Board &6{0}&- has been deleted.
  boardExists: A board by that name already exists.
  boardList: "&6{0}&-: loc=&6{1}&- style=&6{2}&- game=&6{3}&-"
  boardRedrawn: Board &6{0}&- has been redrawn.
  boardStyleChanged: "Board &6{0}&- style changed."
  boardStyleSuggestSave: "Use &f/checkers board save [<new-style-name>]&- to save changes."
  boardStyleSaved: "Board &6{0}&- style saved as &6{1}&-."
  boardStyleBadParam: "Invalid style parameter value &6{0}&-."
  boardTeleportSet: "The teleport-out destination has been set for board &6{0}&-."
  boardTeleportCleared: "The teleport-out destination has been cleared for board &6{0}&-."
  boardTooHigh: This board would be too high for this world.
  boardWouldIntersect: This board would intersect another board (&6{1}&-).
  goingToSpawn: Sending you to spawn point.
  noBoards: There are currently no boards.
  noFreeBoards: There are no free boards to create a game on right now.
  noSuchBoard: No such board &6{0}&-.
  notOnBoard: You are not standing on a board right now.
  squareMessage: "Square &6[{0}]&-, board &6{1}"
  boardDetail:
    board: "Board &6{0}:"
    boardExtents: "Board Extents: &f{0} - {1}"
    boardOrientation: "Board Orientation: &f{0}"
    boardStyle: "Board Style: &f{0}"
    defaultStake: "Default Stake: &f{0} {1}"
    defaultTimeControl: "Default Time Control: &f{0} {1}"
    enclosure: "Enclosure: &f{0}"
    frameWidth: "Frame width: &f{0,number,integer} ({1})"
    game: "Game: &f{0}"
    height: "Height: &f{0,number,integer}"
    lightLevel: "Light level: &f{0,number,integer}"
    locked: (locked)
    pieces: "Pieces: &f{0}&- (white), &f{1}&- (black), "
    squareSize: "Square size: &f{0,number,integer} ({1}/{2})"
    struts: "Enclosure struts: &f{0}"
    teleportDest: "Teleport-out destination: &f{0}"

ControlPanel:
  acceptDrawBtn: "Accept Draw?"
  acceptSwapBtn: "Accept Swap?"
  acceptUndoBtn: "Accept Undo?"
  blackPawnPromotionBtn: "Black Pawn;Promotion"
  boardInfoBtn: ";Board;Info"
  chessInviteReminder: "Type &f/checkers invite <playername>&- to invite someone"
  chessInvitePrompt: "Type a player name to invite.  Left or right-click cancels."
  createGameBtn: ";Create;Game"
  gameInfoBtn: ";Game;Info"
  halfmoveClock: "Halfmove;Clock"
  inviteAnyoneBtn: ";Invite;ANYONE"
  invitePlayerBtn: ";Invite;Player"
  noBtn: ";;No"
  offerDrawBtn: ";Offer;Draw"
  playNumber: "Play Number"
  resignBtn: ";Resign"
  stakeBtn: "Stake;;"
  startGameBtn: ";Start;Game"
  teleportOutBtn: ";Teleport;Out"
  timeControl: "Time Control"
  timeElapsed: "Elapsed"
  timeRemaining: "Remaining"
  undoBtn: ";Undo;Last Move"
  whitePawnPromotionBtn: "White Pawn;Promotion"
  yesBtn: ";;Yes"

Misc:
  AIdefsReloaded: "AI definitions have been reloaded."
  anything: "anything"
  configReloaded: "Configuration (config.yml) has been reloaded"
  boardTeleportSet: "The teleport-out destination has been set for board &6{0}&-."
  boardTeleportCleared: "The teleport-out destination has been cleared for board &6{0}&-."
  globalTeleportSet: "The global teleport-out destination has been set."
  globalTeleportCleared: "The global teleport-out destination has been cleared."
  persistedReloaded: "Persisted board and game data has been reloaded."
  timeControlsReloaded: "Time control definitions have been reloaded."

Flight:
  flightDisabledByAdmin: Checkers board flight has been disabled by a server admin.
  flightDisabled: You are no longer close enough to a Checkers board to fly.
  flightEnabled:
    - You are close enough to a Checkers board to fly.
    - Double-tab Space to toggle flight.
  interactionStopped: You may not interact with the world while flying around a Checkers board!

