Game:
  boardAlreadyHasGame: "That board already has a game on it."
  AIisBusy: "That AI is currently busy playing a game."
  alertPrefix: "&6⛀ &-Game &6{0}&-: "
  autoDeleteFinished: "Finished game auto-deleted."
  autoDeleteNotStarted: "Game auto-deleted (not started within {0})."
  autoDeleteRunning: "Game auto-deleted (no move made within {0})."
  black: "Black"
  cantAffordToStart: "{0} can''t afford to play! (need {1})"
  cantAffordStake: "You can't afford that stake!"
  cantAffordToJoin: "You can''t afford the stake for this game (need {0})!"
  cantWriteArchive: "Can''t write PGN archive {0}: {1}"
  currentGames: "Your current checkers games: {0}"
  gameCreated: "Checkers game &6{0}&- has been created on board &6{1}&-."
  gameDeleted: "Game &6{0}&- has been deleted."
  gameDeletedAlert: "Game deleted by &6{0}&-!"
  gameDetail:
    blackToPlay: "&8Black&- to play"
    clock: "Clock: &8Black&-: {0}, &fWhite&-: {1}"
    halfMoves: "&f{0,number,integer}&- half-moves made"
    invitation: "&6{0}&- has been invited.  Awaiting response."
    moveHistory: "&eMove history:"
    name: "&eGame {0} [{1}]:"
    openInvitation: "Game has an open invitation"
    players: "&6{0}&- (&8Black&-) vs. &6{1}&- (&fWhite&-)."
    rules: "&eRules: &f{0}"
    stake: "&eStake: &f{0}"
    timeControlType: "&eTime Control: &f{0}"
    whiteToPlay: "&fWhite&- to play"
  gameHasStake: "This game has a stake of &f{0}&-."
  gameIsFull: "This game already has two players."
  getStakeBack: "You get your stake of {0} back."
  illegalMove: "Illegal move."
  invalidBoardSize: "This board is the wrong size for ruleset &6{0}&- (size {1,number,integer}x{1,number,integer} required)."
  inviteCooldown: "You must wait {0,number,integer} seconds before sending another open invitation."
  invited: " [invited: &6{0}&-]"
  inviteSent: "An invitation has been sent to &6{0}&-."
  inviteWithdrawn: "Your invitation has been withdrawn."
  joinedGame: "You have joined the checkers game &6{0}&- as &f{1}&-."
  joinPrompt: "Type &f/checkers join&- to join the game."
  joinPromptGlobal: "Type &f/checkers join {0}&- to join the game."
  moveUndone: "Last move undone.  &f{0}&- to play."
  mustContinueJumping: "You must continue to jump."
  mustBeInSetup: "This can only be done during game setup phase."
  newTimeControlPhase: "New time control phase started: &6{0}&-."
  noActiveGame: "No active game - set one with &f/checkers game <name>&-."
  noNegativeStakes: "Negative stakes are not permitted!"
  noActiveGame: "You don't have an active game right now."
  noCurrentGames: "There are no games in progress right now."
  noGame: "(none)"
  noSuchGame: "No such game &6{0}&-."
  notInGame: "You are not in this game!"
  notInvited: "You don't have an invitation for this game."
  notStarted: "The game has not yet started."
  notYourTurn: "It is not your turn."
  nowPlayingBlack: "Side swap!  You are now playing Black."
  nowPlayingWhite: "Side swap!  You are now playing White."
  openInviteCreated: "&6{0}&e has created an open invitation to a Checkers game."
  playerInviteCancelled: "&6Player invitation cancelled."
  playerJoined: "&6{0}&- has joined your game."
  playerNotOnline: "Player {0} is not online."
  playerPlayedMove: "{0}&- played &f{1,number,integer}-{2,number,integer}&-.  Your move, {3}&-."
  playerPlayedChainedMove: "{0}&- played &f{1}&- (move continues...)"
  playerBack: "{0} is back in the game!"
  playerQuit: "{0} quit.  If they don''t rejoin within {1,number,integer} seconds, you can type &f/checkers win&- to win by default."
  result:
    ABANDONED: "&6{0}&- drew with &6{1}&- (game abandoned) in a game of Checkers!"
    DRAW_AGREED: "&6{0}&- drew with &6{1}&- (draw agreed) in a game of Checkers!"
    DRAW_FORCED: "&6{0}&- drew with &6{1}&- (draw forced) in a game of Checkers!"
    FORFEIT: "&6{0}&- beat &6{1}&- (forfeited) in a game of Checkers!"
    RESIGNED: "&6{0}&- beat &6{1}&- (resigned) in a game of Checkers!"
    WIN: "&6{0}&- beat &6{1}&- in a game of Checkers!"
  rulesReminder: "Left-click the &1Rules&- control panel button for a rules summary."
  shouldBeState: "Game should be in state {0}."
  stakeCantBeChanged: "Stake cannot be changed once both players have joined."
  stakeChanged: "Stake for this game is now {0}."
  stakeLocked: "The stake for this game is locked and may not be changed."
  stakeLost: "You lost your stake of {0}."
  stakePaid: "You have paid a stake of {0}."
  stakeReturned: "You get your stake of {0} back."
  stakeTooHigh: "The maximum stake allowed is {0,number,currency}."
  stakeWon: "You have won {0}!"
  started:
    - "Game started!  You are playing &f{0}&-."
    - "To move a piece, look at it while holding {1}, and left-click."
  startPrompt: "Start the game by typing &f/game start&- or pressing the &fStart&- button."
  timeControlSet: "Time control for this game set to {0} ({1})"
  timeControlLocked: "The time control for this game is locked may not be changed."
  timeControlWarning: "You have {0,number,integer} seconds left to move!"
  typeYesOrNo: "Type &f/checkers yes&- to accept, or &f/checkers no&- to decline."
  undoAIWithStake: "You may not undo moves when playing for a stake against the computer."
  white: "White"
  youAreInvited: "You have been invited to this game by &6{0}&-."
  youPlayed: "You played &f{0}-{1}&-."
  yourMove: "It is your move &f({0})&-."

Offers:
  drawOfferAccepted: "Draw offer accepted by &6{0}&-."
  drawOfferDeclined: "Draw offer declined by &6{0}&-."
  drawOfferedOther: "&6{0}&- has offered a draw."
  swapOfferAccepted: "Swap offer accepted by &6{0}&-."
  swapOfferDeclined: "Swap offer declined by &6{0}&-."
  swapOfferedOther: "&6{0}&- has offered to swap sides."
  undoOfferAccepted: "Undo offer accepted by &6{0}&-."
  undoOfferDeclined: "Undo offer declined by &6{0}&-."
  undoOfferedOther: "&6{0}&- wishes to undo their last move."
  youDeclinedDrawOffer: "You have declined the draw offer."
  youDeclinedSwapOffer: "You have declined the swap offer."
  youDeclinedUndoOffer: "You have declined the undo offer."
  youOfferDraw: "You have offered a draw to &6{0}&-."
  youOfferSwap: "You have offered to swap sides with &6{0}&-."
  youOfferUndo: "You have asked &6{0}&- if you may undo your last move."
  typeYesOrNo: "Type &f/checkers yes&- to accept, or &f/checkers no&- to decline."

Board:
  allBoardsRedrawn: All boards have been redrawn.
  boardCantBeDeleted: Board &6{0}&- cannot be deleted because it has a game (&6{1}&-).
  boardCreated: Board &6{0}&- has been created at &f{1}&-.
  boardCreationCancelled: Board creation has been cancelled.
  boardCreationPrompt: Left-click a block to create board &6{0}&-.  Right-click to cancel.
  boardDeleted: Board &6{0}&- has been deleted.
  boardExists: A board by that name already exists.
  boardList: "&6{0}&-: loc=&6{1}&- size=&6{2}&- style=&6{3}&- game=&6{4}&-"
  boardRedrawn: Board &6{0}&- has been redrawn.
  boardStyleChanged: "Board &6{0}&- style changed."
  boardStyleSuggestSave: "Use &f/checkers board save [<new-style-name>]&- to save changes."
  boardStyleSaved: "Board &6{0}&- style saved as &6{1}&-."
  boardStyleBadParam: "Invalid style parameter value &6{0}&-."
  boardTeleportSet: "The teleport-out destination has been set for board &6{0}&-."
  boardTeleportCleared: "The teleport-out destination has been cleared for board &6{0}&-."
  boardTooHigh: This board would be too high for this world.
  boardWouldIntersect: This board would intersect another board (&6{0}&-).
  goingToSpawn: Sending you to spawn point.
  invalidSize: Invalid board size {0,number,integer}.  Valid sizes are 8, 10, 12.
  noBoards: There are currently no boards.
  noFreeBoards: There are no free boards to create a game on right now.
  noSuchBoard: No such board &6{0}&-.
  notOnBoard: You are not standing on a board right now.
  squareMessage: "Square &6[{0}]&-, board &6{1}"
  boardDetail:
    board: "Checkers Board &6{0}:"
    boardExtents: "Board Extents: &f{0} - {1} ({2})"
    boardOrientation: "Board Orientation: &f{0}"
    boardStyle: "Board Style: &f{0}"
    defaultStake: "Default Stake: &f{0} {1}"
    defaultTimeControl: "Default Time Control: &f{0} {1}"
    enclosure: "Enclosure: &f{0}"
    frameWidth: "Frame width: &f{0,number,integer} ({1})"
    game: "Game: &f{0}"
    height: "Height: &f{0,number,integer}"
    lightLevel: "Light level: &f{0,number,integer}"
    locked: (locked)
    pieces: "Pieces: &f{0}&- (white), &f{1}&- (black), "
    squareSize: "Square size: &f{0,number,integer} ({1}/{2})"
    struts: "Enclosure struts: &f{0}"
    teleportDest: "Teleport-out destination: &f{0}"

ControlPanel:
  acceptDrawBtn: "Accept Draw?"
  acceptSwapBtn: "Accept Swap?"
  acceptUndoBtn: "Accept Undo?"
  boardInfoBtn: ";Board;Info"
  inviteReminder: "Type &f/checkers invite <playername>&- to invite someone"
  invitePrompt: "Type a player name to invite.  Left or right-click cancels."
  createGameBtn: ";Create;Game"
  gameInfoBtn: ";Game;Info"
  halfmoveClock: "Halfmove;Clock"
  inviteAnyoneBtn: ";Invite;ANYONE"
  invitePlayerBtn: ";Invite;Player"
  noBtn: ";;No"
  offerDrawBtn: ";Offer;Draw"
  playNumber: "Play Number"
  resignBtn: ";Resign"
  stakeBtn: "Stake;;"
  startGameBtn: ";Start;Game"
  selectRulesBtn: "Rules"
  teleportOutBtn: ";Teleport;Out"
  timeControl: "Time Control"
  timeElapsed: "Elapsed"
  timeRemaining: "Remaining"
  undoBtn: ";Undo;Last Move"
  yesBtn: ";;Yes"

Misc:
  AIdefsReloaded: "AI definitions have been reloaded."
  anything: "anything"
  boardTeleportSet: "The teleport-out destination has been set for board &6{0}&-."
  boardTeleportCleared: "The teleport-out destination has been cleared for board &6{0}&-."
  configReloaded: "Configuration (config.yml) has been reloaded"
  dataSaved: "Checkers board and game data has been saved."
  globalTeleportSet: "The global teleport-out destination has been set."
  globalTeleportCleared: "The global teleport-out destination has been cleared."
  invalidNumeric: "Invalid number: {0}"
  needToWait: "You need to wait {0,number,integer} seconds more."
  otherPlayerMustBeOffline: "You can only do this if the other player has gone offline."
  otherPlayerNeverRejoined: "(The other player hasn't rejoined since the last server restart)"
  persistedReloaded: "Persisted board and game data has been reloaded."
  scoreRecord: "&e{0,number,integer}) &6{1}&-: &f{2}&-"
  timeControlsReloaded: "Time control definitions have been reloaded."

Flight:
  flightDisabledByAdmin: Checkers board flight has been disabled by a server admin.
  flightDisabled: You are no longer close enough to a Checkers board to fly.
  flightEnabled:
    - You are close enough to a Checkers board to fly.
    - Double-tab Space to toggle flight.
  interactionStopped: You may not interact with the world while flying around a Checkers board!

AI:
  AIbusy: "AI is busy right now"
  AIdisabled: "AI games are disabled"
  AIloadError: "AI Loading Error"
  AInotFound: "No such player or AI: {0}"
  AIunexpectedException: "Unexpected Exception in AI: {0}"
  computer: "Computer"
  human: "Human"
  noAvailableAIs:
    - "There are no AIs available to play right now"
    - "(all {0,number,integer} are currently in a game)."
  AIList: "&6{0}&- ({1})&- {2}"
  AIpayout: "payout={0,number,integer}%"
  noFreeAI: "No free AI was found"

SMSIntegration:
  boardInfo: "&1Board Info"
  createGame: "&1Create Game"
  gotoGame: "&1Go to Game"
  gameInfo: "&1Game Info"
  deleteGame: "&4*Delete Game"
  gotoBoard: "&1Go to Board"

Rules:
  headerMessage: "&eRules for &6{0}&e:"
  unknownRuleset: "Unknown ruleset '{0}'."
  EnglishDraughts:
    label: English;Draughts;forced jump
    summary:
      - "You MUST jump if a jump is available."
      - "Men may only move and capture forward."
      - "Kings may move and capture forward or backward."
      - "No flying kings; kings may only move or jump one square."
      - "Black starts."
  EnglishDraughtsNFJ:
    label: English;Draughts;&mforced jump
    summary:
      - "You may choose not to jump if a jump is available."
      - "Men may only move and capture forward."
      - "Kings may move and capture forward or backward."
      - "No flying kings; kings may only move or jump one square."
      - "Black starts."
  InternationalDraughts:
    label: International;Draughts
    summary:
      - "You MUST jump if a jump is available."
      - "Men may only move forward, but may capture backward."
      - "Kings may move and capture forward or backward."
      - "Flying kings; kings may capture at any distance."
      - "White starts."
  BrazilianDraughts:
    label: Brazilian;Draughts
    summary:
      - "You MUST jump if a jump is available."
      - "Men may only move forward, but may capture backward."
      - "Kings may move and capture forward or backward."
      - "Flying kings; kings may capture at any distance."
      - "White starts."
  CanadianCheckers:
    label: Canadian;Checkers
    summary:
      - "You MUST jump if a jump is available."
      - "Men may only move forward, but may capture backward."
      - "Kings may move and capture forward or backward."
      - "Flying kings; kings may capture at any distance."
      - "White starts."
